apiVersion: v1
kind: ConfigMap
metadata:
  name: adhoc-redis-predixy-cfg
  namespace: default
data:
  predixy.conf: |
    Name AdhocPredixy
    Bind 0.0.0.0:7617
    WorkerThreads 16
    BufSize 8192
    Log /storage/logs/adhoc-predixy.log
    LogRotate 1d
    AllowMissLog true
    LogVerbSample 0
    LogDebugSample 0
    LogInfoSample 10000
    LogNoticeSample 1
    LogWarnSample 1
    LogErrorSample 1
    Include cluster.conf
    # Include latency.conf
  cluster.conf: |
    ClusterServerPool {
        MasterReadPriority 60
        StaticSlaveReadPriority 50
        DynamicSlaveReadPriority 50
        RefreshInterval 1
        ServerTimeout 1
        ServerFailureLimit 10
        ServerRetryTimeout 1
        KeepAlive 120
        Servers {
            + 172.21.16.7:7000
            + 172.21.16.7:7001
            + 172.21.16.7:7002
        }
    }
  latency.conf: |
    LatencyMonitor all {
        Commands {
            + all
            - blpop
            - brpop
            - brpoplpush
        }
        TimeSpan {
            + 100
            + 200
            + 300
            + 400
            + 500
            + 600
            + 700
            + 800
            + 900
            + 1000
            + 1200
            + 1400
            + 1600
            + 1700
            + 1800
            + 2000
            + 2500
            + 3000
            + 3500
            + 4000
            + 4500
            + 5000
            + 6000
            + 7000
            + 8000
            + 9000
            + 10000
        }
    }

    LatencyMonitor get {
        Commands {
            + get
        }
        TimeSpan {
            + 100
            + 200
            + 300
            + 400
            + 500
            + 600
            + 700
            + 800
            + 900
            + 1000
        }
    }

    LatencyMonitor set {
        Commands {
            + set
            + setnx
            + setex
        }
        TimeSpan {
            + 100
            + 200
            + 300
            + 400
            + 500
            + 600
            + 700
            + 800
            + 900
            + 1000
        }
    }

    LatencyMonitor blist {
        Commands {
            + blpop
            + brpop
            + brpoplpush
        }
        TimeSpan {
            + 1000
            + 2000
            + 3000
            + 4000
            + 5000
            + 6000
            + 7000
            + 8000
            + 9000
            + 10000
            + 20000
            + 30000
            + 40000
            + 50000
            + 60000
            + 70000
            + 80000
            + 90000
            + 100000
        }
    }