apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-predixy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-predixy
    spec:
      imagePullSecrets:
      - name: docker-registry
      containers:
      - name: redis-predixy
        image: registry.appadhoc.com:30443/redis-predixy:chinamobile
        imagePullPolicy: IfNotPresent
#        command: ["/usr/local/bin/predixy"]
#        args: ["-l","/tmp/$(POD_NAME).log","-c"]
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "0.1"
            memory: 0.1Gi
        volumeMounts:
        - mountPath: /storage/logs
          name: redis-predixy-logs
        - mountPath: /etc/predixy/conf
          name: redis-predixy-cfg
      volumes:
      - name: redis-predixy-logs
        hostPath:
          path: /data/redis-predixy/logs
      - name: redis-predixy-cfg
        configMap:
          name: redis-predixy-cfg
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: predixy
  name: predixy
spec:
  ports:
  - name: proxy
    port: 6379
    targetPort: 7617
  selector:
    app: redis-predixy
